### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by tuxlinuxien** [radicalmind/xeon#3]
Since most/all the code base is from iris. How does it compare?

Why is it fast?

**Comment by radicalmind** [comment]
## Link with Iris

Many of you may think that this project is just an improvement [Iris]((https://github.com/kataras/iris) version because of its easy-API's similiatiries, but that's all.
It's true that this project has a lot of API and performance similarities with the Golang's web framework,  [Iris](https://github.com/kataras/iris).

But why?
No, I didn't "stole" Iris' codebase neither Iris from Xeon. 

Xeon seems to be newest than Iris, but this is not entirely the truth, because author of Iris and me worked internally in the same place, we started from the same codebase at the same time, a year ago.

Back then I wasn't really excited, about his opinions about "open-source idea" and his action to publish the project for free. Iris was a result of hundreds of hours of free-work instead of a paid one, but he convinced me (he's a real diplomat!) to do it.

Of course that Iris' version has nothing to do with this big monster that Iris became later, credits to @kataras. Back then it was more like a router instead of a web framework.

Objectively, Iris is a successor. It succeed to be one of the most trending project on github globe, with:
- 1 contributor
- ~7.000 github stars
- ~400 github watchers
- ~500 github forks
- almost the majority of golang community's friendly tweets and articles
- top #25 on HackerNews over multiple times
- a lot of donations by independent developers and freelancers

So, I decided to take some months off of my job. Take the Iris as it is now and transform it to a next-level-tool.
At __Friday, 02 June 2017__ I published my code with all the enchantments implemented, tested at production-level and reviewed by [@kataras](https://github.com/kataras) himself, he sent me the OK signal to push it with his approval and resigned from any copyrights. I am very thankful for this. I wouldn't be able to develop Xeon without his help and his mental support.

As you will see Xeon has an entirely different structure, some Iris' features that I thought are not nessecary are being removed. 
A lot of improvements and fixes added, its development will be **not** connected with Iris from now and on.

Xeon is a different and unique framework. 

I hope Xeon will get the community's support that Iris had from its zero day!

@tuxlinuxien It's based on Iris but it's not Iris, because its public end-developer API is similar it doesn't mean that this is the same. Xeon has a small performance adv over Iris. You can test it with tools like `ab`, `bombardier` etc...

**Comment by radicalmind** [comment]
## Link with Iris

Many of you may think that this project is just an improvement [Iris]((https://github.com/kataras/iris) version because of its easy-API's similiatiries, but that's all.
It's true that this project has a lot of API and performance similarities with the Golang's web framework,  [Iris](https://github.com/kataras/iris).

But why?
No, I didn't "stole" Iris' codebase neither Iris from Xeon. 

Xeon seems to be newest than Iris, but this is not entirely the truth, because author of Iris and me worked internally in the same place, we started from the same codebase at the same time, a year ago.

Back then I wasn't really excited, about his opinions about "open-source idea" and his action to publish the project for free. Iris was a result of hundreds of hours of free-work instead of a paid one, but he convinced me (he's a real diplomat!) to do it.

Of course that Iris' version has nothing to do with this big monster that Iris became later, credits to @kataras. Back then it was more like a router instead of a web framework.

Objectively, Iris is a successor. It succeed to be one of the most trending project on github globe, with:
- 1 contributor
- ~7.000 github stars
- ~400 github watchers
- ~500 github forks
- almost the majority of golang community's friendly tweets and articles
- top #25 on HackerNews over multiple times
- a lot of donations by independent developers and freelancers

So, I decided to take some months off of my job. Take the Iris as it is now and transform it to a next-level-tool.
At __Friday, 02 June 2017__ I published my code with all the enchantments implemented, tested at production-level and reviewed by [@kataras](https://github.com/kataras) himself, he sent me the OK signal to push it with his approval and resigned from any copyrights. I am very thankful for this. I wouldn't be able to develop Xeon without his help and his mental support.

As you will see Xeon has an entirely different structure, some Iris' features that I thought are not nessecary are being removed. 
A lot of improvements and fixes added, its development will be **not** connected with Iris from now and on.

Xeon is a different and unique framework. 

I hope Xeon will get the community's support that Iris had from its zero day!

@tuxlinuxien Iris is really one of the fastest golang web framework out there, I tested it personally before start this project.

Xeon It's based on Iris but it's not Iris, because its public end-developer API is similar it doesn't mean that this is the same. Xeon has a small performance adv over Iris. You can test it with tools like `ab`, `bombardier` etc...

**Comment by radicalmind** [comment]
Please see https://github.com/radicalmind/xeon/issues/1#issuecomment-305806328.

@tuxlinuxien Hello, its good question and I'm sure all of you love Iris but please try to give Xeon a try too!

Iris is really one of the fastest golang web framework out there, I tested it personally before start this project.

Xeon It's based on Iris but it's not Iris, because its public end-developer API is similar it doesn't mean that this is the same. Xeon has a small performance adv over Iris. You can test it with tools like `ab`, `bombardier` etc...

**Comment by tuxlinuxien** [comment]
@radicalmind the way you are writing your response, the tone, the same grammar mistakes as @kataras ... Sorry, but I can't drink your soup.I have gone through your code, and a lot of files are too similar. Even the examples. Your code is definitely from Iris project, so you should mention it.
![katars-retry](https://cloud.githubusercontent.com/assets/517062/26750091/aee7ae88-484c-11e7-8be6-46aad02115df.png)
![iris-proof](https://cloud.githubusercontent.com/assets/517062/26750107/1efa063a-484d-11e7-835f-8076d46228d1.png)

Iris is maybe a potentially good framework, but the way you have managed it just made people disgusted by your attitude. You have previously ruined your reputation with your behavior,  and you are doing exactly the same thing as before by closing the issue #2. 

Pro tip:
* When you talk about your project, be humble, never say "fastest", "awesome" or "perfect". Your point of view is biased so let the community test it and rank it.
* save yourself some time and move your project to github.com/kataras/xeon. no need to create a new identity. we already know now that @radicalmind and @kataras are the same people.

You have fooled too many people so I will make sure it won't happen again.

**Comment by tuxlinuxien** [comment]
Also, don't edit your comments
![mail](https://cloud.githubusercontent.com/assets/517062/26750211/ab4f68d0-484f-11e7-9454-62c01c01fe52.png)

here is the original response that you gave me. Try to show the community that you have changed. Accept criticism and provide clever responses to **haters**. When you edit their comments, you are just showing you are wrong.
